export { NOW } from "./Now";
export { Group } from "./Group";
export { Easing } from "./Easing";
export type { EasingFunction } from "./Easing";
export { Interpolation } from "./Interpolation";
export type { InterpolationFunction, ARGB, AHSV, AHCL } from "./Interpolation";
export { Tween } from "./Tween";
export { Spring } from "./Spring";
export type { RecursivePartial } from "./RecursivePartial";
export { VERSION } from "./Version";
export { DEFAULTS } from "./Defaults";
export type { IDefaultValues } from "./Defaults";
export type { IUpdateable } from "./IUpdateable";
